/* NEXA AI — from signal to intelligence */
const canvas=document.getElementById('canvas');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x030509);scene.fog=new THREE.FogExp2(0x030509,.03);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,120);camera.position.set(0,.1,8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
scene.add(new THREE.AmbientLight(0xbfdcff,.38));const key=new THREE.PointLight(0xe8f4ff,5,28);key.position.set(0,3,5);scene.add(key);const rim=new THREE.PointLight(0x559dff,7,24);rim.position.set(-5,1,2);scene.add(rim);
const world=new THREE.Group();scene.add(world);const mouse={x:0,y:0,tx:0,ty:0};addEventListener('pointermove',e=>{mouse.tx=e.clientX/innerWidth*2-1;mouse.ty=-(e.clientY/innerHeight*2-1)});
let drag=null,locked=false;addEventListener('pointerdown',e=>drag={x:e.clientX,y:e.clientY});addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.max(Math.abs(dx),Math.abs(dy))>42)goTo(current+(Math.abs(dy)>Math.abs(dx)?(dy<0?1:-1):(dx<0?1:-1)));drag=null});addEventListener('wheel',e=>{if(locked)return;locked=true;goTo(current+(e.deltaY>0?1:-1));setTimeout(()=>locked=false,700)},{passive:true});
const COUNT=innerWidth<700?2200:4400,pos=new Float32Array(COUNT*3),tar=new Float32Array(COUNT*3),vel=new Float32Array(COUNT*3),seed=[];for(let i=0;i<COUNT;i++){const j=i*3,a=Math.random()*Math.PI*2,r=3+Math.random()*8;pos[j]=Math.cos(a)*r;pos[j+1]=(Math.random()-.5)*8;pos[j+2]=Math.sin(a)*r;tar[j]=pos[j];tar[j+1]=pos[j+1];tar[j+2]=pos[j+2];seed[i]=Math.random()}
const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(pos,3));const particles=new THREE.Points(pg,new THREE.PointsMaterial({color:0xb9d9ff,size:innerWidth<700?.027:.038,transparent:true,opacity:.82,blending:THREE.AdditiveBlending,depthWrite:false}));world.add(particles);
function setTarget(fn){for(let i=0;i<COUNT;i++){const p=fn(i,seed[i]),j=i*3;tar[j]=p[0];tar[j+1]=p[1];tar[j+2]=p[2]}}
const TWO=Math.PI*2;
function pointSignal(i,s){const a=s*TWO,r=.2+Math.pow(s,.7)*1.3;return[Math.cos(a)*r,Math.sin(a)*r,Math.sin(a*3+i)*.08]}
function pointInput(i,s){if(i%4===0){const a=s*TWO,r=2.6;return[Math.cos(a)*r,Math.sin(a)*r,Math.sin(a*4)*.2]}const x=(i%22)/21*1.8-.9,y=(Math.floor(i/22)%45)/44*3.7-1.85;return[x,y,Math.sin(i)*.14]}
function pointNetwork(i,s){const a=s*TWO,r=1.2+((i%8)/8)*2.1;return[Math.cos(a)*r,Math.sin(a*2.4)*1.4,Math.sin(a)*r]}
function pointCore(i,s){const a=s*TWO,r=.65+((i%40)/40)*1.9;return[Math.cos(a)*r,Math.sin(a*3+i)*.35,Math.sin(a)*r]}
function pointCreate(i,s){const a=s*TWO,r=1.1+((i%10)/10)*2.8;return[Math.cos(a)*r,Math.sin(a*2)*r*.48,Math.sin(a)*r]}
function pointSpace(i,s){const a=s*TWO,r=1.5+((i%16)/16)*3.4;return[Math.cos(a)*r,Math.sin(a*2+i)*.5,Math.sin(a)*r]}
function pointReveal(i,s){const a=s*TWO,r=.35+((i%24)/24)*2.05;return[Math.cos(a)*r,Math.sin(a)*r*.9,Math.sin(a)*r]}
const targets=[pointSignal,pointInput,pointNetwork,pointCore,pointCreate,pointSpace,pointReveal];
function wire(g,geo,color=0xe9f5ff,opacity=.8){g.add(new THREE.LineSegments(new THREE.WireframeGeometry(geo),new THREE.LineBasicMaterial({color,transparent:true,opacity})))}
function glow(g,geo,color=0x70b9ff,opacity=.1){const m=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide}));g.add(m);return m}
function line(g,a,b,color=0x9fd6ff,opacity=.45){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]);g.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity})))}
function phone(g){wire(g,new THREE.BoxGeometry(2.05,3.8,.24),0xf0f7ff,.92);wire(g,new THREE.BoxGeometry(1.75,3.1,.04),0x76baff,.5);for(let i=0;i<5;i++){const q=new THREE.Mesh(new THREE.BoxGeometry(.35,.08,.04),new THREE.MeshBasicMaterial({color:0xb9e2ff,transparent:true,opacity:.7}));q.position.set(-.6+i*.3,-1.1,.16);g.add(q)}}
function visual(n){const g=new THREE.Group();g.position.y=-.15;
 if(n===0){glow(g,new THREE.SphereGeometry(.55,20,12),0x5caaff,.2);wire(g,new THREE.SphereGeometry(.82,16,10));for(let i=0;i<3;i++){const r=.9+i*.32;const q=new THREE.Mesh(new THREE.RingGeometry(r,r+.012,64),new THREE.MeshBasicMaterial({color:0x9bd3ff,transparent:true,opacity:.5,side:THREE.DoubleSide}));q.rotation.x=Math.PI/2;q.rotation.y=i*.7;g.add(q)}}
 if(n===1){phone(g);for(let i=0;i<6;i++){const q=wire(g,new THREE.BoxGeometry(.42,.42,.12),i%2?0x9bd3ff:0xffffff,.65);q.position.set(i%2?1.8:-1.8,(i-2.5)*.65,0);q.rotation.z=i*.3}}
 if(n===2){for(let i=0;i<12;i++){const a=i/12*TWO,r=1.5+(i%3)*.5,p=[Math.cos(a)*r,Math.sin(a*2)*1.5,Math.sin(a)*r];const q=glow(g,new THREE.SphereGeometry(.09,8,6),0xffffff,.85);q.position.set(...p);if(i>0)line(g,p,[Math.cos((i-1)/12*TWO)*(1.5+((i-1)%3)*.5),Math.sin((i-1)/12*TWO*2)*1.5,Math.sin((i-1)/12*TWO)*(1.5+((i-1)%3)*.5)]);}}
 if(n===3){wire(g,new THREE.IcosahedronGeometry(1.55,2),0xffffff,.9);glow(g,new THREE.SphereGeometry(1.3,24,16),0x5caaff,.12);for(let i=0;i<5;i++){const q=new THREE.Mesh(new THREE.TorusGeometry(1.7+i*.18,.018,8,96),new THREE.MeshBasicMaterial({color:0x9bd3ff,transparent:true,opacity:.5}));q.rotation.set(i*.5,i*.35,0);g.add(q)}}
 if(n===4){for(let i=0;i<5;i++){const q=wire(g,new THREE.BoxGeometry(1.35,.82,.1),i%2?0x9bd3ff:0xffffff,.72);q.position.set((i-2)*1.05,(i%2?1:-1)*.75,Math.sin(i)*.6);q.rotation.y=(i-2)*.22}glow(g,new THREE.SphereGeometry(.6,16,10),0x70b9ff,.18)}
 if(n===5){phone(g);for(let i=0;i<8;i++){const a=i/8*TWO,q=new THREE.LineSegments(new THREE.WireframeGeometry(new THREE.OctahedronGeometry(.32,1)),new THREE.LineBasicMaterial({color:i%2?0x9bd3ff:0xffffff,transparent:true,opacity:.7}));q.position.set(Math.cos(a)*2.6,Math.sin(a*2)*1.1,Math.sin(a)*2.6);g.add(q);line(g,[0,0,0],[q.position.x,q.position.y,q.position.z],0x78baff,.18)}}
 if(n===6){wire(g,new THREE.DodecahedronGeometry(1.8,2),0xffffff,.98);glow(g,new THREE.SphereGeometry(1.28,24,16),0x5caaff,.16);for(let i=0;i<5;i++){const q=new THREE.Mesh(new THREE.TorusGeometry(2+i*.22,.014,8,96),new THREE.MeshBasicMaterial({color:0xbfe5ff,transparent:true,opacity:.6}));q.rotation.set(i*.7,i*.42,0);g.add(q)}}return g}
const data=[['THE SIGNAL','EVERY IDEA STARTS AS A SIGNAL.'],['THE INPUT','NEXA UNDERSTANDS WHAT YOU GIVE IT.'],['THE UNDERSTANDING','IT FINDS THE MEANING BEHIND THE NOISE.'],['THE INTELLIGENCE CORE','FROM NOISE TO CLARITY.'],['THE CREATION','TURN THOUGHT INTO SOMETHING REAL.'],['THE NEXA SPACE','ONE INTELLIGENCE. INFINITE DIRECTIONS.'],['NEXA','TURN IDEAS INTO INTELLIGENCE.']];
let current=0,visualObject=null,transition=1,shake=0,last=performance.now();function updateHUD(){const d=data[current];document.querySelector('.scene-number').textContent=`${String(current+1).padStart(2,'0')} / 07`;document.querySelector('.scene-title').textContent=d[0];document.querySelector('.scene-description').textContent=d[1];document.querySelector('.progress').style.width=`${current/6*100}%`}
function goTo(n){if(n<0||n>6||n===current||transition<1)return;current=n;transition=0;shake=1.5;setTarget(targets[current]);const next=visual(current);next.scale.set(.02,.02,.02);world.add(next);if(visualObject)world.remove(visualObject);visualObject=next;updateHUD();document.getElementById('flash').classList.add('active');setTimeout(()=>document.getElementById('flash').classList.remove('active'),220)}
document.getElementById('enterButton').addEventListener('click',()=>{document.getElementById('intro').classList.add('hidden');document.getElementById('hud').classList.add('active');if(!visualObject){visualObject=visual(0);world.add(visualObject);setTarget(targets[0])}updateHUD()});updateHUD();
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;mouse.x+=(mouse.tx-mouse.x)*.055;mouse.y+=(mouse.ty-mouse.y)*.055;const morph=Math.min(1,transition+=dt*1.25),ease=1-Math.pow(1-morph,3);for(let i=0;i<COUNT;i++){const j=i*3,dx=tar[j]-pos[j],dy=tar[j+1]-pos[j+1],dz=tar[j+2]-pos[j+2],burst=(1-ease)*Math.sin(ease*Math.PI)*(.6+seed[i]*1.8);vel[j]=(vel[j]+dx*.024)*.9;vel[j+1]=(vel[j+1]+dy*.024)*.9;vel[j+2]=(vel[j+2]+dz*.024)*.9;pos[j]+=vel[j]+mouse.x*.002*pos[j+2]+burst*dx*.01;pos[j+1]+=vel[j+1]+mouse.y*.002*pos[j];pos[j+2]+=vel[j+2]}pg.attributes.position.needsUpdate=true;particles.rotation.y+=dt*(.06+Math.abs(mouse.x)*.25);if(visualObject){visualObject.scale.lerp(new THREE.Vector3(1,1,1),.09);visualObject.rotation.y+=dt*(.16+Math.abs(mouse.x)*.42);visualObject.rotation.x+=(mouse.y*.25-visualObject.rotation.x)*.04;visualObject.position.x+=(mouse.x*.4-visualObject.position.x)*.035}shake*=.9;camera.position.x+=(mouse.x*.45+(Math.random()-.5)*shake*.06-camera.position.x)*.035;camera.position.y+=(.1+mouse.y*.22-camera.position.y)*.035;camera.lookAt(0,0,0);renderer.render(scene,camera)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate(performance.now());
